services:
  - type: web
    name: physiq-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: 7788108864:AAFYcVKBCZhjvyf4N41f7iojAW0QCdLRGCo
      - key: WEBHOOK_URL
        value: https://physiq-bot.onrender.com/webhook
