services:
  - type: web
    name: physiq-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    autoDeploy: true
    envVars:
      - key: BOT_TOKEN
        value: your_telegram_bot_token_here
      - key: WEBHOOK_URL
        value: https://your-render-url.onrender.com/webhook
